const double lrmin = log(1.0e-8);
const double lrmax = log(3.0e+1);
const int NR = 800;
const double Deltar = (lrmax - lrmin)/double(NR-1);
const double Deltay = 0.1;
const double Ymin = 0.0;
const int NY = 220;
const double Ymax = (double)NY * Deltay;
const double TWOPI = 2.0 * M_PI;
const double alphastrong = 0.2;
const int NWEZLY = 48;
const double KERCOFF = Deltay  / TWOPI;
const int IterMax = 3;
extern double *h0;
extern double *h_new;
extern double *h_old;
const int NC=3;
const int NF=3;
const double mu2=1;
const double Lambda2 = 0.0588;
const int NN=5001;
const double bmin = 1.0e-4;
const double bmax = 30.0;
