extern void gauleg(double x1, double x2, double * x, double * w, int n);
double Kernel(double lrprim,double phi);
double Kernel_Mass(double lrprim,double phi);
double Kercar(double zx,double zy);
double (*ur2func)(double,double);
double (*Kerfun)(double,double);
double qgauss24(double (*func)(double),double a,double b);
double qgauss(double (*func)(double),double a,double b);
double QGAUSS(double (*func)(double),double a,double b);
double w2(double phi);
double w1(double rprim);
double Lim1(double a);
double Lim2(double b);
double Cc2(double zx);
double Cc1(double zy);
double quad2d(double (*func)(double,double),double rlow,double rhi);
double quad2d_car(double (*func)(double,double),double rlow,double rhi);
double input(double pars,double x);
double Qsat2(double);
void Stars();
void PrintParameters();
void StartProgram();
void SetPoints(int i ,int j,int k,double *pars);
void InitialiseMatrix(double *h1,int n);
void ZeroMatrix(double *h1,int n);
void PrintMatrix(double *h1,int n);
void CopyMatrix(double *h1,double *h2,int n);
void WriteOutErrors(double *h1,double *h2,int n);
void SolveOneStep(int n);
void CheckIntegral(int *n);
double dabs(double arg);
double dmax(double arg1,double arg2);
double dmin(double arg1,double arg2);
double alphalo(double);